
version: '3.8'
services:
  c89_dev:
    build:  
      context: .
      ssh: ["default"]
    container_name: c89_dev 
    entrypoint: [/home/pawn/.entrypoint.sh]
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - ~/.gitconfig:/home/pawn/.gitconfig
      - $SSH_AUTH_SOCK:/ssh-agent
      - ./src:/home/pawn/app
      - ./bash_stuff/bash_history:/home/pawn/.bash_history
      - ./bash_stuff/bash_pref:/home/pawn/.bash_pref
      - ./bash_stuff/entrypoint.sh:/home/pawn/.entrypoint.sh
      - ./src/nvim_config:/home/pawn/.config/nvim
    stdin_open: true
    tty: true
