
version: '3.8'
services:
  c89_dev:
    build: . 
    container_name: cmd_chess
    volumes:
      - .:/home/pawn/app
      - ./bash_stuff/.bash_history:/home/pawn/.bash_history
      - ./bash_stuff/.bash_pref:/home/pawn/.bash_pref
    stdin_open: true
    tty: true
