
version: '3.8'
services:
  c89_dev:
    build:  
      context: .
      ssh: ["default"]
    container_name: c89_dev 
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - ~/.gitconfig:/home/pawn/.gitconfig
      - $SSH_AUTH_SOCK:/ssh-agent
      - .:/home/pawn/app
      - ./bash_stuff/.bash_history:/home/pawn/.bash_history
      - ./bash_stuff/.bash_pref:/home/pawn/.bash_pref
    stdin_open: true
    tty: true
